---
# Put variables for mygalaxy here

galaxy_server_cert: server.crt
galaxy_server_key: server.key

galaxy_user:
  name: sa_galaxy 
  uid: 12345
galaxy_group:
  name: gx_group
  uid: 23456
galaxy_create_user: true
galaxy_separate_privileges: true 
galaxy_privsep_user: root

galaxy_config_files:
  - src: tool_destinations.yml
    dest: "{{ galaxy_config_dir }}/tool_destinations.yml"
galaxy_config_templates:
  - src: job_conf.xml.j2
    dest: "{{ galaxy_config_dir }}/job_conf.xml"
  - src: container_resolvers_conf.xml.j2
    dest: "{{ galaxy_config_dir }}/container_resolvers_conf.xml"

galaxy_config:
  galaxy:
    # ... other settings can go here ...
    conda_auto_init: false
    conda_auto_install: false
    dependency_resolvers: {}
    job_config_file: "{{ galaxy_config_dir}}/job_conf.xml"
    tool_destinations_config_file: "{{ galaxy_config_dir}}/tool_destinations.yml"
    containers_resolvers_config_file: "{{ galaxy_config_dir }/container_resolvers_conf.xml"
```